Release/v1.0.0
Mathmeh/PokePokemons pull request #4
Opened 2024-06-30 14:33 UTC by Mathmeh

* Двустраничное приложение, содержащее RecyclerView с покемонами и с информацией о каждом
* Починил шрифты
![image](https://github.com/Mathmeh/PokePokemons/assets/61705925/a42acc89-1f5f-47f0-a6cd-15a732899677)
![image](https://github.com/Mathmeh/PokePokemons/assets/61705925/ea530d12-70d1-45e1-9721-1ef92daef927)

2024-06-30 21:01 UTC, pzinkevich42innowise requested changes

2024-06-30 21:01 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/agropokemon/Models/Pokemon.kt
> +    }
Это как так?

2024-07-01 00:06 UTC, Mathmeh commented on app/src/main/java/com/example/agropokemon/Models/Pokemon.kt
> +    }
этот кусок кода использовался еще в версии до constraint layout, в кастом лист адаптере

2024-07-04 10:24 UTC, pzinkevich42innowise approved these changes

2024-07-07 14:38 UTC, merged